# Course&nbsp;3:&nbsp;Python&nbsp;for Data Analysis (Assignment)

<center><img src="https://www.import.io/wp-content/uploads/2019/09/data-analysis-blog.jpg" width="600"  title="Python Logo"/></center>

<div class="alert alert-block alert-info">Welcome to your second real set of Python coding problems that will be marked

This time the evaluation will be marked and the mark will be decompose as follow:
- Total: the mark will be on 100%
- Each question is worth of 10%. There is a total of 8 questions, so 80%
- 10% of the mark will be on the cleaning of your code (explicit name for the variable, comments for each line)
- 10% of the mark will be on the respect of the professor's instructions (work given at time, project is named correctly, project is classified is the good category, project is shared with the 2 professors)
</div>

## 0. Presentation of the case study

You will be working for the famous location company Airbnb in NYC. Your Chief of Operation has given you the dataset of all the hosts in NYC with multiple informations on the host: number of bed, number of ratings, ratings, etc.

Unfortunately, the dataset that was given to you is in 2 parts:
- A CSV file called `Airbnb_Part1.csv`
- An Excel file called `Airbnb_Part2.xlsx`
Both of them have been stored on Deepnote under the folder `Data\`

Your mission, tasked by your boss is to help him to understand their market in NYC. For that, he asked you to :
- Consolidate the 2 datasets into 1 dataset
- Make a rapid analysis of the quality of the data
- Clean any disqualities in the data
- Make general statics on their market: number of beds in each neighborhood ? average price in NYC ? total number of reviews in NYC ? Top 3 most representated Property Type? Less representated Room Type among the hosts ?
- Make a focus on the neighborhood of Brookyn: number of beds that it is available in Brooklyn ?

<center><img src="https://cap.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fcap.2F2018.2F05.2F24.2F75cc6ad1-7c73-43a2-850e-e228ad145817.2Ejpeg/1200x630/background-color/ffffff/quality/70/cr/wqkgwqkgQWlyYm5iIC8gQ0FQSVRBTA%3D%3D/location-de-vacances-airbnb-abritel-gites-de-france-quel-site-choisir-1289818.jpg" width="600"  title="Python Logo"/></center>

## 1. Load Data

We will ask you to load the data from the files `Airbnb_Part1.csv` and `Airbnb_Part2.xlsx`
Careful, this time, the data are located in a folder called `Data/`.

Load the data in 2 variables: `df_airbnb_part1` and `df_airbnb_part2`

In [18]:
# Start writing code here...

import pandas as pd
df_airbnb_part1 = pd.read_csv("Airbnb_Part1.csv")
df_airbnb_part2 = pd.read_excel("Airbnb_Part2.xlsx")

## 2. Make some statistics

Make a full analysis of the table. We will ask you a make a detailed report of the data. What can you observe about the data for each table ?

**Tips: Do not hesitate to use multiple blocs of code to divide your analysis**

In [6]:
print("Shape of Airbnb_Part1: ", df_airbnb_part1.shape)
print("Shape of Airbnb_Part2: ", df_airbnb_part2.shape)

Shape of Airbnb_Part1:  (30471, 11)
Shape of Airbnb_Part2:  (8, 11)

**Airbnb_Part1**

In [7]:
# Start writing code here...
df_airbnb_part1.head(5)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
0,1,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,Entire home/apt,11249.0,1.0,0,145,NaN
1,2,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,Private room,11206.0,1.0,1,37,NaN
2,3,NaN,Sunny Room in Harlem,Manhattan,Apartment,Private room,10032.0,1.0,1,28,NaN
3,4,2008-06-26,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,Entire home/apt,10024.0,3.0,0,199,NaN
4,5,2008-06-26,Trendy Times Square Loft,Manhattan,Apartment,Private room,10036.0,3.0,39,549,96.0

In [9]:
print("All variable types in Airbnb_Part1")
df_airbnb_part1.dtypes

All variable types in Airbnb_Part1

Host Id                   int64
Host Since               object
Name                     object
Neighbourhood            object
Property Type            object
Room Type                object
Zipcode                 float64
Beds                    float64
Number Of Reviews         int64
Price                     int64
Review Scores Rating    float64
dtype: object

In [10]:
#print("Description of Airbnb_Part1:")
df_airbnb_part1.describe(include='all')

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
count,30471.000000,30468,30471,30471,30468,30471,30337.000000,30386.000000,30471.000000,30471.000000,22155.000000
unique,NaN,2240,29410,5,19,3,NaN,NaN,NaN,NaN,NaN
top,NaN,2014-02-10,Charming West Village studio,Manhattan,Apartment,Entire home/apt,NaN,NaN,NaN,NaN,NaN
freq,NaN,70,15,16030,27097,17021,NaN,NaN,NaN,NaN,NaN
mean,15236.000000,NaN,NaN,NaN,NaN,NaN,10584.833767,1.529981,12.021496,163.572512,91.993230
std,8796.364363,NaN,NaN,NaN,NaN,NaN,921.365486,1.015256,21.982473,197.764772,8.850373
min,1.000000,NaN,NaN,NaN,NaN,NaN,1003.000000,0.000000,0.000000,10.000000,20.000000
25%,7618.500000,NaN,NaN,NaN,NaN,NaN,10017.000000,1.000000,0.000000,80.000000,89.000000
50%,15236.000000,NaN,NaN,NaN,NaN,NaN,10065.000000,1.000000,3.000000,125.000000,94.000000
75%,22853.500000,NaN,NaN,NaN,NaN,NaN,11216.000000,2.000000,13.000000,195.000000,100.000000
max,30471.000000,NaN,NaN,NaN,NaN,NaN,99135.000000,16.000000,257.000000,10000.000000,100.000000

In [11]:
list(df_airbnb_part1.columns)

['Host Id',
 'Host Since',
 'Name',
 'Neighbourhood',
 'Property Type',
 'Room Type',
 'Zipcode',
 'Beds',
 'Number Of Reviews',
 'Price',
 'Review Scores Rating']

**Airbnb_Part2**

In [12]:
df_airbnb_part2.head(5)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
0,30472,2015-08-31,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,Entire home/apt,10036.0,2,0,200,NaN
1,30473,2015-08-31,Luxury apt with spectacular views,Manhattan,Apartment,Entire home/apt,10036.0,2,0,850,NaN
2,30474,2015-08-31,10 Mins to Time Square/two floors,Queens,Apartment,Entire home/apt,11101.0,5,0,300,NaN
3,30475,2015-08-31,"1BR ocean view & F,Q train st",Brooklyn,Apartment,Private room,11224.0,2,0,125,NaN
4,30476,2015-08-31,Amazing Private Room,Brooklyn,Other,Private room,11206.0,1,0,80,NaN

In [13]:
print("All variable types in Airbnb_Part2")
df_airbnb_part2.dtypes

All variable types in Airbnb_Part2

Host Id                         object
Host Since              datetime64[ns]
Name                            object
Neighbourhood                   object
Property Type                   object
Room Type                       object
Zipcode                        float64
Beds                             int64
Number Of Reviews                int64
Price                            int64
Review Scores Rating           float64
dtype: object

In [14]:
df_airbnb_part2.describe(include='all')

<ipython-input-14-5bf4780a6832>:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_airbnb_part2.describe(include='all')

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
count,8.0,7,7,7,7,7,7.000000,8.000000,8.0,8.000000,1.0
unique,8.0,1,7,3,3,2,NaN,NaN,NaN,NaN,NaN
top,30472.0,2015-08-31 00:00:00,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,Private room,NaN,NaN,NaN,NaN,NaN
freq,1.0,7,1,3,5,4,NaN,NaN,NaN,NaN,NaN
first,NaN,2015-08-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,NaN,2015-08-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,10676.142857,3.500000,0.0,417.500000,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,603.996531,4.440077,0.0,570.288148,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,10025.000000,1.000000,0.0,35.000000,0.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,10036.000000,1.000000,0.0,80.000000,0.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,11101.000000,2.000000,0.0,162.500000,0.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,11155.500000,2.750000,0.0,437.500000,0.0
max,NaN,NaN,NaN,NaN,NaN,NaN,11224.000000,14.000000,0.0,1670.000000,0.0

In [15]:
list(df_airbnb_part2.columns)

['Host Id',
 'Host Since',
 'Name',
 'Neighbourhood',
 'Property Type',
 'Room Type',
 'Zipcode',
 'Beds',
 'Number Of Reviews',
 'Price',
 'Review Scores Rating']

## 3. Easy pre-processing of the data

What can you observe on `df_airbnb_part2`. Look at the dataset. It is not too large !

In [16]:
df_airbnb_part2

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
0,30472,2015-08-31,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,Entire home/apt,10036.0,2,0,200,NaN
1,30473,2015-08-31,Luxury apt with spectacular views,Manhattan,Apartment,Entire home/apt,10036.0,2,0,850,NaN
2,30474,2015-08-31,10 Mins to Time Square/two floors,Queens,Apartment,Entire home/apt,11101.0,5,0,300,NaN
3,30475,2015-08-31,"1BR ocean view & F,Q train st",Brooklyn,Apartment,Private room,11224.0,2,0,125,NaN
4,30476,2015-08-31,Amazing Private Room,Brooklyn,Other,Private room,11206.0,1,0,80,NaN
5,30477,2015-08-31,Charming private female room: UWS,Manhattan,Apartment,Private room,10025.0,1,0,35,NaN
6,30478,2015-08-31,Huge Beautiful Bedroom - Astoria,Queens,House,Private room,11105.0,1,0,80,NaN
7,TOTAL,NaT,NaN,NaN,NaN,NaN,NaN,14,0,1670,0.0

Your answer: ....



1.   Most Properpty Types are Apartment.
2.   There is a wide range of price in Manhattan.

Write a code to clean / delete the messy data. The new cleaned dataframe will be called `df_airbnb_part2_clean`. Tips: think about using indexing/slicing ;)

In [17]:
# Start writing code here...

from sklearn import preprocessing

x = df_airbnb_part2["Price"].values.reshape(-1, 1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df_airbnb_part2['Price'] = pd.DataFrame(x_scaled)

df_airbnb_part2

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
0,30472,2015-08-31,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,Entire home/apt,10036.0,2,0,0.100917,NaN
1,30473,2015-08-31,Luxury apt with spectacular views,Manhattan,Apartment,Entire home/apt,10036.0,2,0,0.498471,NaN
2,30474,2015-08-31,10 Mins to Time Square/two floors,Queens,Apartment,Entire home/apt,11101.0,5,0,0.162080,NaN
3,30475,2015-08-31,"1BR ocean view & F,Q train st",Brooklyn,Apartment,Private room,11224.0,2,0,0.055046,NaN
4,30476,2015-08-31,Amazing Private Room,Brooklyn,Other,Private room,11206.0,1,0,0.027523,NaN
5,30477,2015-08-31,Charming private female room: UWS,Manhattan,Apartment,Private room,10025.0,1,0,0.000000,NaN
6,30478,2015-08-31,Huge Beautiful Bedroom - Astoria,Queens,House,Private room,11105.0,1,0,0.027523,NaN
7,TOTAL,NaT,NaN,NaN,NaN,NaN,NaN,14,0,1.000000,0.0

## 4. Combine the dataset

The file, being in 2 parts. We would like to combine them into 1 file. Is this a `concat` ou `merge` operation ? Do the right operation looking at the documentation :
- `concat` : https://pandas.pydata.org/docs/reference/api/pandas.concat.html
- `merge` : https://pandas.pydata.org/docs/reference/api/pandas.merge.html

We will call the obtained table: `df_airbnb`

In [26]:
# Start writing code here...

data = [df_airbnb_part1, df_airbnb_part2.iloc[:7]]
df_airbnb = pd.concat(data)
df_airbnb.reset_index(drop=True, inplace=True)
total_calculation = pd.concat([df_airbnb_part1, df_airbnb_part2]).sum()
total_calculation_df = pd.DataFrame(total_calculation).T
df_airbnb = pd.concat([df_airbnb, total_calculation_df])
df_airbnb.reset_index(drop=True, inplace=True)
df_airbnb.tail(10)

<ipython-input-26-e2e0d26c6c96>:6: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  total_calculation = pd.concat([df_airbnb_part1, df_airbnb_part2]).sum()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
30469,30470,2015-08-31,Cute East Village Studio Sept 8-16,Manhattan,Apartment,Entire home/apt,10009.0,1.0,0.0,105.0,NaN
30470,30471,2015-08-31,Upper West Side Luxury Apartment,Manhattan,Apartment,Entire home/apt,10023.0,1.0,0.0,240.0,NaN
30471,30472,2015-08-31 00:00:00,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,Entire home/apt,10036.0,2.0,0.0,200.0,NaN
30472,30473,2015-08-31 00:00:00,Luxury apt with spectacular views,Manhattan,Apartment,Entire home/apt,10036.0,2.0,0.0,850.0,NaN
30473,30474,2015-08-31 00:00:00,10 Mins to Time Square/two floors,Queens,Apartment,Entire home/apt,11101.0,5.0,0.0,300.0,NaN
30474,30475,2015-08-31 00:00:00,"1BR ocean view & F,Q train st",Brooklyn,Apartment,Private room,11224.0,2.0,0.0,125.0,NaN
30475,30476,2015-08-31 00:00:00,Amazing Private Room,Brooklyn,Other,Private room,11206.0,1.0,0.0,80.0,NaN
30476,30477,2015-08-31 00:00:00,Charming private female room: UWS,Manhattan,Apartment,Private room,10025.0,1.0,0.0,35.0,NaN
30477,30478,2015-08-31 00:00:00,Huge Beautiful Bedroom - Astoria,Queens,House,Private room,11105.0,1.0,0.0,80.0,NaN
30478,NaN,NaN,NaN,NaN,NaN,NaN,321186835.0,46518.0,366307.0,4987558.0,2038110.0

## 5. Data Manipulation

List all the columns names of your dataframe `df_airbnb`

In [28]:
# Start writing code here...
list(df_airbnb.columns)

['Host Id',
 'Host Since',
 'Name',
 'Neighbourhood',
 'Property Type',
 'Room Type',
 'Zipcode',
 'Beds',
 'Number Of Reviews',
 'Price',
 'Review Scores Rating']

Give the size of your dataframe `df_airbnb`

In [27]:
# Start writing code here...
print("Shape of df_airbnb: ", end = '')
df_airbnb.shape

Shape of df_airbnb:

(30479, 11)

Make a brief statistics summary of your whole table

In [29]:
# Start writing code here...

df_airbnb.describe(include='all')

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
count,30478.0,30475,30478,30478,30475,30478,3.034500e+04,30394.000000,30479.000000,3.047900e+04,2.215600e+04
unique,30478.0,2241,29416,5,19,3,NaN,NaN,NaN,NaN,NaN
top,1.0,2014-02-10,Charming West Village studio,Manhattan,Apartment,Entire home/apt,NaN,NaN,NaN,NaN,NaN
freq,1.0,70,15,16033,27102,17024,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,2.116901e+04,3.060538,24.036681,3.272235e+02,1.839782e+02
std,NaN,NaN,NaN,NaN,NaN,NaN,1.843741e+06,266.818516,2098.236522,2.856826e+04,1.369186e+04
min,NaN,NaN,NaN,NaN,NaN,NaN,1.003000e+03,0.000000,0.000000,1.000000e+01,2.000000e+01
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.001700e+04,1.000000,0.000000,8.000000e+01,8.900000e+01
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.006500e+04,1.000000,3.000000,1.250000e+02,9.400000e+01
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.121600e+04,2.000000,13.000000,1.950000e+02,1.000000e+02
max,NaN,NaN,NaN,NaN,NaN,NaN,3.211868e+08,46518.000000,366307.000000,4.987558e+06,2.038110e+06

## 6. Get insights from the Brooklyn neighborhood

We are now interested in getting the number of host in each neighborhood.

In [30]:
# Start writing code here...

df_airbnb['Neighbourhood'].value_counts()

Manhattan        16033
Brooklyn         11675
Queens            2278
Bronx              345
Staten Island      147
Name: Neighbourhood, dtype: int64

Which neighboorhood has the most numbers of host ?

Your answer : ...

**Brooklyn**

Select the host that only host in the Neightbourhood of Brooklyn. Store them in a variable called `df_brooklyn`

In [31]:
# Start writing code here...

df_brooklyn = df_airbnb[df_airbnb['Neighbourhood']=='Brooklyn']
df_brooklyn

,Host Id,Host Since,Name,Neighbourhood,Property Type,Room Type,Zipcode,Beds,Number Of Reviews,Price,Review Scores Rating
0,1,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,Entire home/apt,11249.0,1.0,0.0,145.0,NaN
1,2,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,Private room,11206.0,1.0,1.0,37.0,NaN
5,6,2008-07-25,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,Entire home/apt,11222.0,1.0,4.0,149.0,100.0
7,8,2008-08-15,"Colorful, quiet, & near the subway!",Brooklyn,Apartment,Private room,11201.0,1.0,80.0,90.0,94.0
10,11,2008-08-27,THE PUTNAM,Brooklyn,Apartment,Entire home/apt,11221.0,2.0,14.0,170.0,98.0
...,...,...,...,...,...,...,...,...,...,...,...
30465,30466,2015-08-31,• Sunny Artist Home in Greenpoint •,Brooklyn,Apartment,Entire home/apt,11222.0,1.0,0.0,100.0,NaN
30466,30467,2015-08-31,Beautiful parkfront sanctuary,Brooklyn,Apartment,Entire home/apt,11226.0,1.0,0.0,160.0,NaN
30467,30468,2015-08-31,"Colorful, comfortable artsy 2 bdrm",Brooklyn,Apartment,Entire home/apt,11238.0,3.0,0.0,127.0,NaN
30474,30475,2015-08-31 00:00:00,"1BR ocean view & F,Q train st",Brooklyn,Apartment,Private room,11224.0,2.0,0.0,125.0,NaN
30475,30476,2015-08-31 00:00:00,Amazing Private Room,Brooklyn,Other,Private room,11206.0,1.0,0.0,80.0,NaN

Calculate the number of beds that it is available in Brooklyn

In [32]:
# Start writing code here...

df_brooklyn['Beds'].sum()

18135.0

## 7. Data Quality issue

How many clients don't have a rating ?

In [33]:
# Start writing code here...

no_rating = df_airbnb['Review Scores Rating'].isna()
no_rating.sum()

8323

In [ ]:
# Start writing code here...

## 8. Get Insights

What is the average price in NYC ? Store this price in a variable called `mean_price` and print it into the console.

Tips: Give a nice print ;)

In [34]:
# Start writing code here...
avg_price = df_airbnb['Price'].mean()
print("Average price in NYC: ", avg_price,"$")

Average price in NYC:  327.22353095574005 $

What is the total number of reviews in NYC ? Store this total reviews in a variable called `total_reviews` and print it into the console.

Tips: Give a nice print ;)

In [35]:
# Start writing code here...

valid_reviews = df_airbnb['Review Scores Rating'].notna()
total_reviews = valid_reviews.sum()
print("Total number of reviews in NYC:", total_reviews)

Total number of reviews in NYC: 22156

What are the Top 3 most representated Property Type of the hosts ? Store it in a variable called `top3_property_type` and display only the Top 3

In [36]:
# Start writing code here...

top3_property_type = df_airbnb['Property Type'].value_counts().head(3)
print("Top 3 most represented property types:")
print(top3_property_type)

Top 3 most represented property types:
Apartment    27102
House         2090
Loft           753
Name: Property Type, dtype: int64

What is the less representated Room Type among the hosts ? Store it in a variable called `bottom_room_type` and display only this room type

In [37]:
# Start writing code here...

bottom_room_type = df_airbnb['Property Type'].value_counts().tail(3)
print("Top 3 most represented property types:")
print(bottom_room_type)

Top 3 most represented property types:
Lighthouse    1
Chalet        1
Castle        1
Name: Property Type, dtype: int64

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=7b3aa472-a71f-4453-9fa4-cee24f417af3' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>